version: "3.3"
services:

  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: true
    volumes:
      - ./tests:/app/tests
      - ./metrics:/app/metrics
    # command: pytest
    # environment:
    #   - DEBUG=true
    command: pytest -s