version: "3.3"
services:

  api:
    build: .
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./metrics:/app/metrics
    command: /start-reload.sh
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
