name: Test Metrics
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'metrics/*'
    - 'api/*'
    - '.github/workflows/test.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  #   # Everyday at 01:00am GMT+1

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest
      # pytest -s
